Add models
RCDD-202110-TUR-BEW/backend-capstone-turkey-voluntera pull request #22
Opened 2022-02-04 10:22 UTC by halitbatur

# Create DB models

- Created DB models.
- Implement a discriminate function for the user model.

NOTE: This PR is made by @ZuluNovember, I had to revert the old PR and create a new one since it was not approved by @Shrreya

2022-02-05 08:08 UTC, Shrreya requested changes
Great work overall! Specially setting up the discriminator schema and finding the right use for embedding and referencing.

I have a bunch of suggestions for improvement. Hope this helps. 🙂

2022-02-05 08:08 UTC, Shrreya commented on src/models/user.js
> +    },
If `skills` are optional then consider adding a `default` property as empty array.

2022-02-05 08:08 UTC, Shrreya commented on src/models/user.js
> +    },
Following up from @ibraheemhajjar's suggestion in the previous PR, can you create a virtual field for `age` on this model?

2022-02-07 17:13 UTC, Shrreya approved these changes
@ZuluNovember Impeccable work! 🚀

2022-02-07 17:28 UTC, ibraheemhajjar approved these changes
good job @ZuluNovember

2022-02-07 17:52 UTC, merged