Local auth
RCDD-202110-TUR-BEW/backend-capstone-turkey-voluntera pull request #41
Opened 2022-02-19 15:06 UTC by ZuluNovember

Closes #6 

# Implement local sign-in strategy
- Implemented local authentication on `auth/signin` endpoint.
- It uses common callback and signout controllers with google auth.

2022-02-22 15:52 UTC, Kishimoto96 reviewed
Thanks for the great work, do we need a signup function also in the routes or are we just gonna use google auth for signing up?

2022-02-22 22:53 UTC, Kishimoto96 approved these changes
perfect thank you so much for your consideration

2022-02-23 16:05 UTC, Shrreya requested changes
Just 1 small change request, rest looks good!

2022-02-23 16:05 UTC, Shrreya commented on src/utils/localAuth.js
> +    }
```suggestion
    } catch (err) {
      logger.error(err);
      return callback(null, false, err);
    }
```

2022-02-24 08:39 UTC, Shrreya approved these changes

2022-02-25 17:30 UTC, merged